development:
  server: "http://glowing-robot-6850.herokuapp.com:80/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://glowing-robot-6850.herokuapp.com:80/faye"
  secret_token: "secret"
  signature_expiration: 3600 # one hour
